name: CI / CD - Morse Code

on: 
  pull_request:
    branches: [pipfile-experiment]
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Python and Pipenv
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}


      - name: Turn on 'editable' mode
        run: |
          pipenv install -e .

      - name: Run pytest
        run: |
          pipenv install pytest
          pipenv --venv
          pipenv run python -m pytest

  deliver:
    if: github.event_name != 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: "3.10"

      - name: Build package
        run: |
          pipenv install build
          pipenv run python -m build .

      #  publish to PyPI Test server
      # - name: Publish to TestPyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #     repository-url: https://test.pypi.org/legacy/
